# Generated by Django 4.0.5 on 2022-07-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_coment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
